---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast-consumer
  template:
    metadata:
      labels:
        app: hazelcast-consumer
    spec:
      containers:
        - name: hazelcast-consumer
          image: consumer:0.0.1
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-consumer
spec:
  type: LoadBalancer
  selector:
    app: hazelcast-consumer
  ports:
  - name: app
    port: 8080
